Add isShutdown() method to check if ShardManager has been shut down
discord-jda/JDA pull request #2495
Opened 2023-07-04 21:01 UTC by jandie1505

[contributing]: https://jda.wiki/contributing/contributing/

## Pull Request Etiquette

- [x] I have checked the PRs for upcoming features/bug fixes.
- [x] I have read the [contributing guidelines][contributing].

### Changes

- [ ] Internal code
- [x] Library interface (affecting end-user code) 
- [ ] Documentation
- [ ] Other: \_____ 

Closes Issue: NaN

## Description

Adds a method to check if a ShardManager is shut down.

2023-07-04 21:55 UTC, CheesyGamer77 requested changes

2023-07-04 21:55 UTC, CheesyGamer77 commented on src/main/java/net/dv8tion/jda/api/sharding/DefaultShardManager.java
> +        return this.shutdown.get();
See [initial discussion in Discord](https://discord.com/channels/125227483518861312/125227483518861312/1125903549847584798). This is a logic error.

2023-07-04 22:01 UTC, jandie1505 commented
I close this due to the logic error and will re-open it when it is fixed.

2023-07-05 10:35 UTC, jandie1505 commented
I changed the method that it checks if the ScheduledExecutorService of the DefaultShardManager is terminated.

JDAs can still be running if isShutdown() returns true. If it would make more sense to not return true until all the JDAs are also shut down, i can add that as well.

2023-07-14 14:16 UTC, closed without merging