Add support for bulk banning users
discord-jda/JDA pull request #2630
Opened 2024-03-16 20:20 UTC by MinnDevelopment

[contributing]: https://jda.wiki/contributing/contributing/

## Pull Request Etiquette

- [x] I have checked the PRs for upcoming features/bug fixes.
- [x] I have read the [contributing guidelines][contributing].

### Changes

- [ ] Internal code
- [x] Library interface (affecting end-user code) 
- [ ] Documentation
- [ ] Other: \_____ 

Closes Issue: NaN

## Description

Adds support for the new bulk-ban endpoint.

Reference: https://github.com/discord/discord-api-spec/commit/aeb7e2c173bb701743f4d24f75dc3fc4affd4b17

2024-03-16 20:32 UTC, Xirado requested changes

2024-03-16 20:32 UTC, Xirado commented on src/main/java/net/dv8tion/jda/api/entities/BulkBanResponse.java
> +     * List if successfully banned users.
```suggestion
     * List of successfully banned users.
```

2024-03-16 20:32 UTC, Xirado commented on src/main/java/net/dv8tion/jda/api/entities/BulkBanResponse.java
> +     * List if users which could not be banned.
```suggestion
     * List of users which could not be banned.
```

2024-03-17 19:11 UTC, MinnDevelopment commented on src/main/java/net/dv8tion/jda/api/entities/Guild.java
> +     *     <br>One of the users does not exist</li>
```suggestion
     *     <br>The user does not exist</li>
```

2024-03-30 18:54 UTC, merged