Add `JDA#listenOnce`
discord-jda/JDA pull request #2683
Opened 2024-05-27 17:17 UTC by freya022

[contributing]: https://jda.wiki/contributing/contributing/

## Pull Request Etiquette

- [X] I have checked the PRs for upcoming features/bug fixes.
- [X] I have read the [contributing guidelines][contributing].

### Changes

- [X] Internal code
- [X] Library interface (affecting end-user code) 
- [ ] Documentation
- [ ] Other: \_____ 

Closes Issue: NaN

## Description

Adds an helper method to listen for an event, once.

2024-05-27 18:27 UTC, duncte123 commented
There is an `addEventLister` method on the shardManager, maybe this helper method could be added to that as well?

2024-06-15 17:10 UTC, freya022 commented
> There is an `addEventLister` method on the shardManager, maybe this helper method could be added to that as well?

This would make things more complicated, if someone has a use case where you'd need to listen once for an event across all shards, let me know

2024-07-02 02:24 UTC, AshlyneS commented
Just a quick thought, but I believe these would also be benifical. 💕
```java
<E extends GenericEvent> Task<E> listenOnce(Class<E> type, Predicate<? super E> filter);

<E extends GenericEvent> Task<E> listenOnce(Class<E> type, Predicate<? super E> filter, Duration duration, @Nullable Runnable callback);
``` 

Otherwise at least some way to `listenOnce(new SomethingCommonlyImplemented(argA, argB, etc))`

2024-07-06 09:54 UTC, freya022 commented
> Just a quick thought, but I believe these would also be benifical. 💕
> 
> ```java
> <E extends GenericEvent> Task<E> listenOnce(Class<E> type, Predicate<? super E> filter);
> 
> <E extends GenericEvent> Task<E> listenOnce(Class<E> type, Predicate<? super E> filter, Duration duration, @Nullable Runnable callback);
> ```
> 
> Otherwise at least some way to
> 
> ```java
> jda.listenOnce(new SomethingCommonlyImplemented(argA, argB, etc));
> ```

After [discussing](https://ptb.discord.com/channels/125227483518861312/1236273393230286898/1257631039065423915):
- The two first overloads would just be shortcuts, except they bring more confusion on what each parameter is, this will not be added.
- The last overload might be used in interactions which require waiting for user feedback, each class would configure the event, filters and the outcome of each step. This won't be added as JDA remains a low-level enough library, this type of usage can easily be achieved using an utility class such as:
```java
public abstract class OnceFactory<E extends GenericEvent> {
    private final JDA jda;

    public OnceFactory(JDA jda) {
        this.jda = jda;
    }

    protected Class<E> getType();

    protected void configure(Once.Builder<E> builder);

    public Task<E> create() {
        final var builder = jda.listenOnce(getType());
        configure(builder);

        return builder.submit();
    }
}
```

2024-07-21 11:04 UTC, MinnDevelopment requested changes

2024-07-21 11:04 UTC, MinnDevelopment commented on src/main/java/net/dv8tion/jda/api/utils/Once.java
> +            if (timeoutCallback != null)
Use the return value of `completeExceptionally` to check if the future was actually completed by this call. This way you prevent race-conditions where both callbacks can run. Do the same below for the success cases.

2024-07-21 11:04 UTC, MinnDevelopment commented on src/main/java/net/dv8tion/jda/api/utils/Once.java
> +                    future.completeExceptionally(e);
This never does anything, you can't complete a future twice.

2024-07-21 11:04 UTC, MinnDevelopment commented on src/main/java/net/dv8tion/jda/api/utils/Once.java
> +        if (filters.stream().allMatch(p -> p.test(casted)))
This needs to do exception handling, if any of the filters or callbacks throw, we should de-register the listener as well.

2024-07-21 16:54 UTC, MinnDevelopment commented on src/main/java/net/dv8tion/jda/api/utils/Once.java
> +                return;
```suggestion
            if (!future.completeExceptionally(new TimeoutException()))
                return;
```

2024-07-21 16:54 UTC, MinnDevelopment commented on src/main/java/net/dv8tion/jda/api/utils/Once.java
> +                    LOG.error("An error occurred while running the timeout callback", e);
Rethrow if this is an `Error`

2024-07-21 16:54 UTC, MinnDevelopment commented on src/main/java/net/dv8tion/jda/api/utils/Once.java
> +            if (future.completeExceptionally(e))
Rethrow errors

2024-07-21 16:56 UTC, MinnDevelopment commented on src/main/java/net/dv8tion/jda/api/utils/Once.java
> +    private Once(@Nonnull Once.Builder<E> builder)
I'd prefer doing this the standard way of passing parameters. As is, this class is very difficult to extend.

2024-07-21 17:51 UTC, MinnDevelopment commented on src/main/java/net/dv8tion/jda/api/utils/Once.java
> +package net.dv8tion.jda.api.utils;
Missing copyright

2024-07-27 07:39 UTC, MinnDevelopment approved these changes

2024-08-02 18:30 UTC, merged