Added Safety Alerts Channel
discord-jda/JDA pull request #2725
Opened 2024-08-28 21:20 UTC by RealYusufIsmail

[contributing]: https://jda.wiki/contributing/contributing/

## Pull Request Etiquette

- [x] I have checked the PRs for upcoming features/bug fixes.
- [x] I have read the [contributing guidelines][contributing].

### Changes

- [x] Internal code
- [ ] Library interface (affecting end-user code) 
- [ ] Documentation
- [ ] Other: \_____ 

Closes Issue: NaN

## Description

Added getSafetyAlertsChannel allowing you to get the channel to which Discord sends alerts to.

2024-08-28 21:28 UTC, freya022 requested changes
You don't need the put the fully qualified name in the javadocs if the type is already imported

2024-08-28 21:28 UTC, freya022 commented on src/main/java/net/dv8tion/jda/api/managers/GuildManager.java
> +     */
```suggestion
    /** Used to rest the safety alerts channel field */
```

2024-08-28 21:28 UTC, freya022 commented on src/main/java/net/dv8tion/jda/api/managers/GuildManager.java
> +     * Sets the safety alerts {@link net.dv8tion.jda.api.entities.channel.concrete.TextChannel TextChannel} of this {@link net.dv8tion.jda.api.entities.Guild Guild}.
```suggestion
     * Sets the safety alerts {@link TextChannel} of this {@link Guild}.
```

2024-08-28 21:28 UTC, freya022 commented on src/main/java/net/dv8tion/jda/api/managers/GuildManager.java
> +     *         The new safety alerts channel for this {@link net.dv8tion.jda.api.entities.Guild Guild}
```suggestion
     *         The new safety alerts channel for this {@link Guild}
```

2024-08-28 21:28 UTC, freya022 commented on src/main/java/net/dv8tion/jda/internal/entities/GuildImpl.java
> +    @Override
```suggestion
    @Nullable
    @Override
```

2024-08-28 21:46 UTC, freya022 approved these changes
Looks fine, I haven't compared to similar classes though

2024-10-05 15:56 UTC, DV8FromTheWorld approved these changes
LGTM!

2024-10-05 15:57 UTC, merged