Replace `GatewayIntent#GUILD_EMOJIS_AND_STICKERS` with `GUILD_EXPRESSIONS`
discord-jda/JDA pull request #2755
Opened 2024-10-16 12:03 UTC by freya022

[contributing]: https://jda.wiki/contributing/contributing/

## Pull Request Etiquette

- [X] I have checked the PRs for upcoming features/bug fixes.
- [X] I have read the [contributing guidelines][contributing].

### Changes

- [ ] Internal code
- [X] Library interface (affecting end-user code) 
- [X] Documentation
- [ ] Other: \_____ 

Closes Issue: NaN

## Description

Updates the intent to match Discord's name, will be clearer for #2753

If the user does not migrate to the new intent, and has activated cache flags that require the `GUILD_EXPRESSIONS` intents, the cache flags will get disabled and a warning will be logged.

2024-11-01 11:35 UTC, MinnDevelopment commented
> If the user does not migrate to the new intent, and has activated cache flags that require the GUILD_EXPRESSIONS intents, the cache flags will get disabled and a warning will be logged.

I don't think it will be disabled, since the check will include both regardless. I'll consider writing a test for this.

2024-11-01 11:35 UTC, MinnDevelopment requested changes

2024-11-01 11:35 UTC, MinnDevelopment commented on src/main/java/net/dv8tion/jda/api/requests/GatewayIntent.java
> +    @ForRemoval(deadline = "5.2.0")
```suggestion
    @ForRemoval(deadline = "5.3.0")
    @ReplaceWith("GUILD_EXPRESSIONS")
```

2024-11-01 16:58 UTC, freya022 commented
True, as it uses the raw intents, it sees both the old and new intent enabled.

2024-11-03 13:32 UTC, MinnDevelopment commented on src/main/java/net/dv8tion/jda/api/requests/GatewayIntent.java
> +            }
```suggestion
                intents.add(GUILD_EXPRESSIONS);
```

2024-11-03 14:12 UTC, merged